# Generated by Django 4.0 on 2021-12-18 14:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=5142741589, unique=True, validators=[users.models.validate_phone], verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
