# Generated by Django 4.0 on 2021-12-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile'),
            preserve_default=False,
        ),
    ]
