# Generated by Django 4.0 on 2021-12-20 12:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_contact_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[users.models.validate_phone], verbose_name='phone number'),
        ),
    ]
