# Generated by Django 4.0 on 2021-12-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('owner', 'profile')},
        ),
    ]
