# Generated by Django 4.0 on 2021-12-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_contact_phone_alter_profile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=8755147348, max_length=10),
            preserve_default=False,
        ),
    ]
