# Generated by Django 4.0 on 2021-12-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_messages', to='users.profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_for',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_messages', to='users.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(to='chats.Message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('owner', 'chat_with')},
        ),
    ]
