# Generated by Django 4.0 on 2021-12-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_contact_profile'),
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='uid',
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_messages', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_messages', to='users.profile'),
        ),
    ]
