# Generated by Django 4.0 on 2021-12-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_uid_alter_message_sender_alter_message_sent_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='uid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='uid',
            field=models.UUIDField(),
        ),
    ]
