# Generated by Django 4.0 on 2021-12-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_contact_profile_alter_contact_unique_together'),
        ('chats', '0004_a_alter_chat_uid_alter_message_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_with', to='users.profile'),
        ),
    ]
