# Generated by Django 4.0 on 2021-12-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_contact_phone'),
        ('chats', '0005_alter_chat_chat_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='out_messages', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_messages', to='users.profile'),
        ),
    ]
