# Generated by Django 4.0 on 2021-12-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_chat_messages'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
    ]
