# Generated by Django 4.0 on 2021-12-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_contact_phone'),
        ('chats', '0010_alter_chat_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('owner', 'chat_with')},
        ),
    ]
