# Generated by Django 4.0 on 2021-12-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_alter_chat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
